"use client";
import { useEffect, useMemo, useState } from "react";

type Debt = { id:string; name:string; currentBalance:string|number; interestRate:string|number|null; monthlyPayment:string|number|null };
type Payment = { id:string; date:string; interestAmount:string|number; principalAmount:string|number; extraPrincipal:string|number; taxReliefEstimate:string|number; note?:string|null };
type LoanPart = { id:string; name:string; loanType:"ANNUITY"|"LINEAR"|"INTEREST_ONLY"; originalPrincipal:string|number; currentBalance:string|number; interestRate:string|number; monthlyPayment:string|number|null; startDate:string; endDate:string|null };
type InvestmentAsset = { id:string; name:string; currentValue:string|number };
type Mortgage = { id:string; name:string; endDate:string|null; fixedRateEndDate:string|null; wozValue:string|number|null; taxRate:string|number|null; eigenwoningforfaitRate:string|number|null; taxYear:number|null; debt:Debt; payments:Payment[]; loanParts:LoanPart[]; balanceHistory:unknown[]; extraPayments:unknown[] };
type ProjectionRow={month:number;date:Date;balance:number;interest:number;principal:number;extra:number;gross:number;taxRelief:number;net:number;investment:number};
type Scenario={label:string;kind:"repay"|"invest";amount:number;months:number;payoffDate:Date|null;interest:number;taxRelief:number;netCost:number;interestSaved:number;timeSaved:number;investment:number;rows:ProjectionRow[]};
type StrategyYear={year:number;repayBalance:number;investBalance:number;repayInvestment:number;investInvestment:number;repayBox3:number;investBox3:number;repayTaxRelief:number;investTaxRelief:number;repayNetWorth:number;investNetWorth:number;difference:number};
const money=(v:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(Number.isFinite(v)?v:0);
const styles:Record<string,React.CSSProperties>={
 page:{width:"100%",maxWidth:1500,margin:"0 auto",padding:"24px 26px 40px",display:"grid",gap:18,boxSizing:"border-box",color:"var(--foreground)"},
 card:{border:"1px solid var(--border)",borderRadius:14,padding:18,minWidth:0,background:"var(--card)",boxShadow:"0 1px 2px rgba(15,23,42,.03)"},
 field:{width:"100%",padding:"10px 12px",border:"1px solid var(--border)",borderRadius:9,background:"var(--background)",color:"var(--foreground)",boxSizing:"border-box",marginTop:6},
 muted:{color:"var(--muted-foreground)",fontSize:13},
 label:{fontSize:13,fontWeight:550,display:"block",minWidth:0},
};
function Icon({children}:{children:string}){return <span aria-hidden="true" style={{width:34,height:34,display:"inline-grid",placeItems:"center",borderRadius:11,background:"rgba(16,185,129,.10)",color:"#059669",fontSize:18,flexShrink:0}}>{children}</span>}
function addMonths(date:Date,months:number){const d=new Date(date);d.setMonth(d.getMonth()+months);return d;}
function monthDiff(from:Date,to:Date){return Math.max(1,(to.getFullYear()-from.getFullYear())*12+to.getMonth()-from.getMonth());}
function annuityPayment(balance:number,annualRate:number,months:number){if(months<=0)return balance;const r=annualRate/1200;if(r===0)return balance/months;return balance*r/(1-Math.pow(1+r,-months));}
function durationText(months:number){if(!Number.isFinite(months)||months<=0)return "—";const y=Math.floor(months/12),m=months%12;return `${y} jaar${m?` en ${m} mnd`:""}`;}
function dateText(date:Date|null){return date?date.toLocaleDateString("nl-NL",{month:"long",year:"numeric"}):"Niet binnen prognose";}
function projectMortgage(opts:{balance:number;rate:number;payment:number;endDate:string|null;loanType:"ANNUITY"|"LINEAR"|"INTEREST_ONLY";extra:number;oneTimeExtra?:number;invest:number;startInvestment?:number;returnRate:number;taxRate:number;ewfTaxMonthly:number}){
 const now=new Date(),maxMonths=600,r=opts.rate/1200,remaining=opts.endDate?monthDiff(now,new Date(opts.endDate)):360;
 let balance=Math.max(0,opts.balance-Math.max(0,opts.oneTimeExtra||0)),investment=Math.max(0,opts.startInvestment||0),totalInterest=0,totalRelief=0,totalNet=0;
 let regularPayment=opts.payment>0?opts.payment:annuityPayment(balance,opts.rate,remaining);
 const linearPrincipal=opts.loanType==="LINEAR"?balance/remaining:0;
 const rows:ProjectionRow[]=[];
 for(let month=1;month<=maxMonths&&balance>0.005;month++){
   const interest=balance*r;
   let principal=0;
   if(opts.loanType==="INTEREST_ONLY") principal=month>=remaining?balance:0;
   else if(opts.loanType==="LINEAR") principal=Math.min(balance,linearPrincipal);
   else principal=Math.max(0,Math.min(balance,regularPayment-interest));
   const extra=Math.min(Math.max(0,balance-principal),opts.extra);
   if(principal+extra<=0&&interest>=regularPayment&&opts.loanType!=="INTEREST_ONLY") break;
   const gross=interest+principal+extra;
   const taxRelief=Math.max(0,interest*opts.taxRate-opts.ewfTaxMonthly);
   const net=Math.max(0,gross-taxRelief);
   balance=Math.max(0,balance-principal-extra);
   investment=(investment+opts.invest)*Math.pow(1+opts.returnRate/100,1/12);
   totalInterest+=interest;totalRelief+=taxRelief;totalNet+=net;
   rows.push({month,date:addMonths(now,month),balance,interest,principal,extra,gross,taxRelief,net,investment});
 }
 return {rows,months:rows.length,payoffDate:balance<=0.005&&rows.length?rows[rows.length-1].date:null,interest:totalInterest,taxRelief:totalRelief,netCost:totalNet,investment};
}
function projectInvestmentAfterBox3(opts:{start:number;monthly:number;returnRate:number;months:number;box3StartYear:number;box3Rate:number;exemptResult:number}){
 const monthlyGrowth=Math.pow(1+opts.returnRate/100,1/12),now=new Date();
 let value=Math.max(0,opts.start),yearOpening=value,yearContributions=0,totalTax=0;
 const values:number[]=[],taxByYear=new Map<number,number>();
 for(let month=1;month<=opts.months;month++){
   const date=addMonths(now,month),year=date.getFullYear();
   value=(value+Math.max(0,opts.monthly))*monthlyGrowth;
   yearContributions+=Math.max(0,opts.monthly);
   const next=addMonths(now,month+1),isYearEnd=next.getFullYear()!==year||month===opts.months;
   if(isYearEnd){
     const gain=value-yearOpening-yearContributions;
     const taxable=year>=opts.box3StartYear?Math.max(0,gain-Math.max(0,opts.exemptResult)):0;
     const tax=Math.max(0,taxable*Math.max(0,opts.box3Rate));
     value=Math.max(0,value-tax);totalTax+=tax;taxByYear.set(year,tax);
     yearOpening=value;yearContributions=0;
   }
   values.push(value);
 }
 return {values,taxByYear,totalTax,endValue:value};
}
function ProjectionChart({base,extra,fixedRateEndDate,endDate}:{base:ProjectionRow[];extra:ProjectionRow[];fixedRateEndDate:string|null;endDate:string|null}){
 const width=900,height=270,pad=34,maxMonth=Math.max(base.length,extra.length,1),maxBalance=Math.max(base[0]?.balance||0,extra[0]?.balance||0,1);
 const pts=(rows:ProjectionRow[])=>rows.filter((_,i)=>i%Math.max(1,Math.floor(rows.length/100))===0||i===rows.length-1).map(r=>`${pad+(r.month/maxMonth)*(width-pad*2)},${pad+(r.balance/maxBalance)*(height-pad*2)}`).join(" ");
 const marker=(date:string|null)=>{if(!date)return null;const m=monthDiff(new Date(),new Date(date));if(m<0||m>maxMonth)return null;const x=pad+(m/maxMonth)*(width-pad*2);return <line x1={x} y1={pad} x2={x} y2={height-pad} stroke="currentColor" strokeOpacity=".25" strokeDasharray="5 5"/>};
 return <div style={{overflowX:"auto"}}><svg viewBox={`0 0 ${width} ${height}`} style={{width:"100%",minWidth:620,height:"auto"}} role="img" aria-label="Prognose hypotheekschuld"><line x1={pad} y1={height-pad} x2={width-pad} y2={height-pad} stroke="currentColor" strokeOpacity=".2"/><line x1={pad} y1={pad} x2={pad} y2={height-pad} stroke="currentColor" strokeOpacity=".2"/>{marker(fixedRateEndDate)}{marker(endDate)}<polyline points={pts(base)} fill="none" stroke="#64748b" strokeWidth="3"/><polyline points={pts(extra)} fill="none" stroke="#059669" strokeWidth="3"/><text x={pad} y={18} fontSize="12" fill="currentColor">Hypotheekschuld</text><text x={width-pad-120} y={18} fontSize="11" fill="#64748b">basis</text><text x={width-pad-62} y={18} fontSize="11" fill="#059669">scenario</text></svg></div>;
}

export default function HypotheekPage(){
 const [mortgages,setMortgages]=useState<Mortgage[]>([]),[available,setAvailable]=useState<Debt[]>([]),[investmentAssets,setInvestmentAssets]=useState<InvestmentAsset[]>([]),[selected,setSelected]=useState(""),[name,setName]=useState("Mijn hypotheek"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [mortgageId,setMortgageId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[interest,setInterest]=useState(""),[principal,setPrincipal]=useState(""),[extra,setExtra]=useState("0"),[taxRate,setTaxRate]=useState("37.56"),[wozValue,setWozValue]=useState(""),[eigenwoningforfaitRate,setEigenwoningforfaitRate]=useState("0.35"),[taxYear,setTaxYear]=useState(String(new Date().getFullYear())),[note,setNote]=useState("");
 const [editingPayment,setEditingPayment]=useState<{id:string;mortgageId:string;date:string;interestAmount:string;principalAmount:string;extraPrincipal:string;taxReliefEstimate:string;note:string}|null>(null);
 const [customExtra,setCustomExtra]=useState("400"),[oneTimeExtra,setOneTimeExtra]=useState("0"),[investmentAmount,setInvestmentAmount]=useState("400"),[investmentReturn,setInvestmentReturn]=useState("7"),[loanType,setLoanType]=useState<"ANNUITY"|"LINEAR"|"INTEREST_ONLY">("ANNUITY");
 const [box3Rate,setBox3Rate]=useState("36"),[box3ExemptResult,setBox3ExemptResult]=useState("1800"),[box3StartYear,setBox3StartYear]=useState("2028");
 async function load(){setError("");try{const r=await fetch("/api/mortgage");const d=await r.json();if(!r.ok)throw Error(d.error||"Ophalen mislukt");setMortgages(d.mortgages||[]);setAvailable(d.availableDebts||[]);setInvestmentAssets(d.investmentAssets||[]);if(!mortgageId&&d.mortgages?.[0])setMortgageId(d.mortgages[0].id);}catch(e){setError(e instanceof Error?e.message:"Fout bij ophalen");}}
 useEffect(()=>{void load();},[]);
 const selectedMortgage=mortgages.find(m=>m.id===mortgageId);
 useEffect(()=>{
  if(!selectedMortgage)return;
  setWozValue(selectedMortgage.wozValue!=null?String(selectedMortgage.wozValue):"");
  setTaxRate(selectedMortgage.taxRate!=null?String(selectedMortgage.taxRate):"37.56");
  setEigenwoningforfaitRate(selectedMortgage.eigenwoningforfaitRate!=null?String(selectedMortgage.eigenwoningforfaitRate):"0.35");
  setTaxYear(selectedMortgage.taxYear!=null?String(selectedMortgage.taxYear):String(new Date().getFullYear()));
 },[selectedMortgage?.id]);
 const taxRateFraction=Math.max(0,Math.min(100,Number(taxRate)||0))/100;
 const wozValueNum=Math.max(0,Number(wozValue)||0);
 const eigenwoningforfaitRateNum=Math.max(0,Number(eigenwoningforfaitRate)||0);
 const annualEigenwoningforfait=wozValueNum*(eigenwoningforfaitRateNum/100);
 const monthlyEigenwoningforfait=annualEigenwoningforfait/12;
 const annualEwfTax=annualEigenwoningforfait*taxRateFraction;
 const monthlyEwfTax=annualEwfTax/12;
 const monthlyEstimates=useMemo(()=>mortgages.map(m=>{const balance=Number(m.debt.currentBalance)||0,rate=Math.max(0,Number(m.debt.interestRate)||0),gross=Math.max(0,Number(m.debt.monthlyPayment)||0),interestEstimate=balance*rate/1200,tax=Math.max(0,Math.min(100,Number(m.taxRate)||0))/100,ewf=(Math.max(0,Number(m.wozValue)||0)*(Math.max(0,Number(m.eigenwoningforfaitRate)||0)/100))/12,relief=Math.max(0,interestEstimate*tax-ewf*tax);return{id:m.id,balance,rate,gross,interestEstimate,relief,net:Math.max(0,gross-relief),hasPayment:m.debt.monthlyPayment!==null&&m.debt.monthlyPayment!==undefined&&m.debt.monthlyPayment!==""};}),[mortgages]);
 const monthlyTotals=monthlyEstimates.reduce((a,x)=>({gross:a.gross+x.gross,interest:a.interest+x.interestEstimate,relief:a.relief+x.relief,net:a.net+x.net}),{gross:0,interest:0,relief:0,net:0});
 const totals=useMemo(()=>mortgages.reduce((a,m)=>{a.balance+=Number(m.debt.currentBalance)||0;a.interest+=m.payments.reduce((x,p)=>x+Number(p.interestAmount),0);a.principal+=m.payments.reduce((x,p)=>x+Number(p.principalAmount)+Number(p.extraPrincipal),0);a.relief+=m.payments.reduce((x,p)=>x+Number(p.taxReliefEstimate),0);return a;},{balance:0,interest:0,principal:0,relief:0}),[mortgages]);
 const interestNum=Number(interest||0),principalNum=Number(principal||0),extraNum=Number(extra||0),estimatedRelief=Math.max(0,interestNum*taxRateFraction-monthlyEwfTax);
 const currentInvestmentValue=useMemo(()=>investmentAssets.reduce((sum,a)=>sum+(Number(a.currentValue)||0),0),[investmentAssets]);
 const calculator=useMemo(()=>{
  if(!selectedMortgage)return null;
  const balance=Math.max(0,Number(selectedMortgage.debt.currentBalance)||0),rate=Math.max(0,Number(selectedMortgage.debt.interestRate)||0),payment=Math.max(0,Number(selectedMortgage.debt.monthlyPayment)||0);
  const tax=Math.max(0,Math.min(100,Number(selectedMortgage.taxRate??taxRate)||0))/100;
  const woz=Math.max(0,Number(selectedMortgage.wozValue??wozValue)||0),ewfRate=Math.max(0,Number(selectedMortgage.eigenwoningforfaitRate??eigenwoningforfaitRate)||0)/100,ewfTaxMonthly=woz*ewfRate*tax/12;
  const invest=Math.max(0,Number(investmentAmount)||0),ret=Math.max(-99,Number(investmentReturn)||0),startInvestment=currentInvestmentValue;
  const base=projectMortgage({balance,rate,payment,endDate:selectedMortgage.endDate,loanType,extra:0,invest:0,startInvestment,returnRate:ret,taxRate:tax,ewfTaxMonthly});
  const amounts=[100,200,400,500];
  const repay=amounts.map(amount=>{const p=projectMortgage({balance,rate,payment,endDate:selectedMortgage.endDate,loanType,extra:amount,invest:0,startInvestment,returnRate:ret,taxRate:tax,ewfTaxMonthly});return{label:`€${amount} extra aflossen`,kind:"repay" as const,amount,...p,interestSaved:Math.max(0,base.interest-p.interest),timeSaved:Math.max(0,base.months-p.months)};});
  const custom=Math.max(0,Number(customExtra)||0),oneTime=Math.min(balance,Math.max(0,Number(oneTimeExtra)||0)),cp=projectMortgage({balance,rate,payment,endDate:selectedMortgage.endDate,loanType,extra:custom,oneTimeExtra:oneTime,invest:0,startInvestment,returnRate:ret,taxRate:tax,ewfTaxMonthly});
  const ip=projectMortgage({balance,rate,payment,endDate:selectedMortgage.endDate,loanType,extra:0,invest,startInvestment,returnRate:ret,taxRate:tax,ewfTaxMonthly});
  const scenarios:Scenario[]=[{label:"Niets extra aflossen",kind:"repay",amount:0,...base,interestSaved:0,timeSaved:0},{...repay[0]},{...repay[1]},{...repay[2]},{...repay[3]},{label:`€${custom.toLocaleString("nl-NL")} extra aflossen`,kind:"repay",amount:custom,...cp,interestSaved:Math.max(0,base.interest-cp.interest),timeSaved:Math.max(0,base.months-cp.months)},{label:`€${invest.toLocaleString("nl-NL")} beleggen`,kind:"invest",amount:invest,...ip,interestSaved:0,timeSaved:0}];
  const currentInterest=balance*rate/1200,currentPrincipal=loanType==="LINEAR"?(selectedMortgage.endDate?balance/monthDiff(new Date(),new Date(selectedMortgage.endDate)):Math.max(0,payment-currentInterest)):loanType==="INTEREST_ONLY"?0:Math.max(0,payment-currentInterest);
  const yearly=(rows:ProjectionRow[])=>{const map=new Map<number,{year:number;interest:number;principal:number;extra:number;taxRelief:number;net:number;endBalance:number;investment:number}>();for(const row of rows){const year=row.date.getFullYear(),x=map.get(year)||{year,interest:0,principal:0,extra:0,taxRelief:0,net:0,endBalance:row.balance,investment:row.investment};x.interest+=row.interest;x.principal+=row.principal;x.extra+=row.extra;x.taxRelief+=row.taxRelief;x.net+=row.net;x.endBalance=row.balance;x.investment=row.investment;map.set(year,x);}return [...map.values()];};
  const targetMonths=selectedMortgage.endDate?monthDiff(new Date(),new Date(selectedMortgage.endDate)):base.months;
  const targetPayment=annuityPayment(Math.max(0,balance-oneTime),rate,targetMonths);
  const requiredExtra=Math.max(0,targetPayment-payment);
  const horizon=Math.max(base.months,1),boxRate=Math.max(0,Number(box3Rate)||0)/100,boxExempt=Math.max(0,Number(box3ExemptResult)||0),boxStart=Math.max(new Date().getFullYear(),Math.floor(Number(box3StartYear)||2028));
  const repayInvest=projectInvestmentAfterBox3({start:startInvestment,monthly:0,returnRate:ret,months:horizon,box3StartYear:boxStart,box3Rate:boxRate,exemptResult:boxExempt});
  const investInvest=projectInvestmentAfterBox3({start:startInvestment,monthly:invest,returnRate:ret,months:horizon,box3StartYear:boxStart,box3Rate:boxRate,exemptResult:boxExempt});
  const strategyYears:StrategyYear[]=[];
  const years=[...new Set(Array.from({length:horizon},(_,i)=>addMonths(new Date(),i+1).getFullYear()))];
  for(const year of years){
    const lastMonth=Math.min(horizon,Array.from({length:horizon},(_,i)=>i+1).filter(m=>addMonths(new Date(),m).getFullYear()===year).pop()||horizon);
    const baseRow=[...base.rows].reverse().find(r=>r.month<=lastMonth);
    const cpRow=[...cp.rows].reverse().find(r=>r.month<=lastMonth);
    const repayBalance=cpRow&&lastMonth<=cp.months?cpRow.balance:0,investBalance=baseRow?.balance??0;
    const repayInvestment=repayInvest.values[lastMonth-1]??repayInvest.endValue,investInvestment=investInvest.values[lastMonth-1]??investInvest.endValue;
    const repayTaxRelief=cp.rows.filter(r=>r.date.getFullYear()===year).reduce((a,r)=>a+r.taxRelief,0),investTaxRelief=base.rows.filter(r=>r.date.getFullYear()===year).reduce((a,r)=>a+r.taxRelief,0);
    const repayNetWorth=repayInvestment-repayBalance,investNetWorth=investInvestment-investBalance;
    strategyYears.push({year,repayBalance,investBalance,repayInvestment,investInvestment,repayBox3:repayInvest.taxByYear.get(year)||0,investBox3:investInvest.taxByYear.get(year)||0,repayTaxRelief,investTaxRelief,repayNetWorth,investNetWorth,difference:investNetWorth-repayNetWorth});
  }
  return {balance,rate,payment,base,customProjection:cp,scenarios,currentInterest,currentPrincipal,ewfTaxMonthly,yearly:yearly(cp.rows),oneTime,requiredExtra,strategyYears,repayBox3Total:repayInvest.totalTax,investBox3Total:investInvest.totalTax,boxStart,boxRate,boxExempt};
 },[selectedMortgage,customExtra,oneTimeExtra,investmentAmount,investmentReturn,loanType,taxRate,wozValue,eigenwoningforfaitRate,currentInvestmentValue,box3Rate,box3ExemptResult,box3StartYear]);

 async function link(){setBusy(true);setError("");try{const r=await fetch("/api/mortgage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({debtId:selected,name})});const d=await r.json();if(!r.ok)throw Error(d.error||"Koppelen mislukt");await load();}catch(e){setError(e instanceof Error?e.message:"Fout");}finally{setBusy(false);}}
 async function saveMortgageDates(id:string,endDate:string,fixedRateEndDate:string){setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/mortgage",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"updateMortgageDates",mortgageId:id,endDate:endDate||null,fixedRateEndDate:fixedRateEndDate||null})});const d=await r.json();if(!r.ok)throw Error(d.error||"Datums opslaan mislukt");setNotice("Hypotheekdatums opgeslagen.");await load();}catch(e){setError(e instanceof Error?e.message:"Datums opslaan mislukt");}finally{setBusy(false);}}
 async function saveTaxSettings(){if(!mortgageId){setError("Selecteer eerst een hypotheek.");return;}setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/mortgage",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"updateTaxSettings",mortgageId,wozValue,taxRate,eigenwoningforfaitRate,taxYear:Number(taxYear)})});const d=await r.json();if(!r.ok)throw Error(d.error||"Fiscale gegevens opslaan mislukt");setNotice("WOZ- en belastinggegevens opgeslagen.");await load();}catch(e){setError(e instanceof Error?e.message:"Fiscale gegevens opslaan mislukt");}finally{setBusy(false);}}
 async function addPayment(){setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/mortgage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createPayment",mortgageId,date,interestAmount:interest,principalAmount:principal,extraPrincipal:extra,taxReliefEstimate:estimatedRelief,note})});const d=await r.json();if(!r.ok)throw Error(d.error||"Opslaan mislukt");setNotice(`Betaling opgeslagen. Nieuw saldo: ${money(Number(d.newBalance))}`);setInterest("");setPrincipal("");setExtra("0");setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"Fout");}finally{setBusy(false);}}
 function beginEdit(m:Mortgage,p:Payment){setEditingPayment({id:p.id,mortgageId:m.id,date:new Date(p.date).toISOString().slice(0,10),interestAmount:String(p.interestAmount),principalAmount:String(p.principalAmount),extraPrincipal:String(p.extraPrincipal),taxReliefEstimate:String(p.taxReliefEstimate),note:p.note||""});setError("");setNotice("");}
 async function saveEdit(){if(!editingPayment)return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/mortgage",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(editingPayment)});const d=await r.json();if(!r.ok)throw Error(d.error||"Wijzigen mislukt");setNotice(`Betaling gewijzigd. Nieuw saldo: ${money(Number(d.newBalance))}`);setEditingPayment(null);await load();}catch(e){setError(e instanceof Error?e.message:"Wijzigen mislukt");}finally{setBusy(false);}}
 async function removePayment(paymentId:string){if(!window.confirm("Weet je zeker dat je deze betaling wilt verwijderen? De bijbehorende aflossing wordt teruggedraaid in het actuele hypotheeksaldo."))return;setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/mortgage",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({paymentId})});const d=await r.json();if(!r.ok)throw Error(d.error||"Verwijderen mislukt");if(editingPayment?.id===paymentId)setEditingPayment(null);setNotice(`Betaling verwijderd. Nieuw saldo: ${money(Number(d.newBalance))}`);await load();}catch(e){setError(e instanceof Error?e.message:"Verwijderen mislukt");}finally{setBusy(false);}}
 const metric=(icon:string,label:string,value:string,sub:string,accent=false)=><article style={{...styles.card,padding:16,background:accent?"rgba(16,185,129,.055)":"var(--card)",borderColor:accent?"rgba(16,185,129,.25)":"var(--border)"}}><div style={{display:"flex",alignItems:"center",gap:11}}><Icon>{icon}</Icon><div style={{minWidth:0}}><div style={styles.muted}>{label}</div><strong style={{fontSize:24,lineHeight:1.35,color:accent?"#059669":"var(--foreground)",fontVariantNumeric:"tabular-nums"}}>{value}</strong><div style={{...styles.muted,fontSize:11}}>{sub}</div></div></div></article>;
 const input=(label:string,value:string,onChange:(v:string)=>void,props:React.InputHTMLAttributes<HTMLInputElement>={})=><label style={styles.label}>{label}<input {...props} style={styles.field} value={value} onChange={e=>onChange(e.target.value)}/></label>;
 return <main style={styles.page}>
 <header style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h1 style={{fontSize:30,fontWeight:750,margin:0,letterSpacing:"-.6px"}}>⌂ Hypotheek</h1><p style={{...styles.muted,margin:"3px 0 0"}}>Overzicht van je hypotheek(en), maandlasten, rente, aflossing en fiscale voordelen.</p></div><span style={{border:"1px solid rgba(16,185,129,.22)",background:"rgba(16,185,129,.06)",padding:"9px 13px",borderRadius:10,fontSize:12,color:"#059669"}}>％ Renteaftrek indicatief</span></header>
 {error&&<div role="alert" style={{...styles.card,borderColor:"#ef4444",color:"#dc2626"}}>{error}</div>}{notice&&<div role="status" style={{...styles.card,borderColor:"#10b981",color:"#059669"}}>{notice}</div>}
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}>{metric("▣","Totale hypotheekschuld",money(totals.balance),"Actueel saldo van alle hypotheekdelen")}{metric("▦","Bruto maandlast",money(monthlyTotals.gross),"Rente + aflossing (regulier)")}{metric("%","Geschatte rente per maand",money(monthlyTotals.interest),"Op basis van huidig saldo en rente")}{metric("◉","Geschatte renteaftrek",money(monthlyTotals.relief),`Bij ${taxRate}% belastingtarief`)}{metric("€","Netto maandlast",money(monthlyTotals.net),"Na belastingvoordeel (indicatief)",true)}</section>
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.65fr) minmax(310px, .95fr)",gap:16,alignItems:"start"}} className="mortgage-main-grid">
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><Icon>⌂</Icon><div><h2 style={{margin:0,fontSize:19}}>Hypotheekdelen</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Actuele gegevens en maandlasten per deel.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(235px,1fr))",gap:12}}>{mortgages.map(m=>{const x=monthlyEstimates.find(v=>v.id===m.id)!;return <article key={m.id} style={{border:"1px solid var(--border)",borderRadius:12,padding:15,minWidth:0}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><strong>{m.debt.name||m.name}</strong><span style={{fontSize:11,color:"#047857",background:"rgba(16,185,129,.1)",borderRadius:20,padding:"4px 8px"}}>Hypotheek</span></div><div style={{...styles.muted,marginTop:7}}>Rente {x.rate.toLocaleString("nl-NL",{maximumFractionDigits:2})}%</div><div style={{fontSize:26,fontWeight:750,marginTop:3,fontVariantNumeric:"tabular-nums"}}>{money(x.balance)}</div><div style={{...styles.muted,marginTop:12,display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:9}}><div><div>Maandtermijn</div><strong style={{color:"var(--foreground)",fontSize:15}}>{x.hasPayment?money(x.gross):"Niet ingesteld"}</strong></div><div><div>Rente per maand</div><strong style={{color:"var(--foreground)",fontSize:15}}>{money(x.interestEstimate)}</strong></div><div><div>Geschatte netto termijn</div><strong style={{color:"#059669",fontSize:15}}>{x.hasPayment?money(x.net):"—"}</strong></div><div><div>Rentepercentage</div><strong style={{color:"var(--foreground)",fontSize:15}}>{x.rate.toLocaleString("nl-NL")} %</strong></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8,marginTop:14,paddingTop:12,borderTop:"1px solid var(--border)"}}><label style={styles.label}>Einddatum hypotheek<input type="date" defaultValue={m.endDate?new Date(m.endDate).toISOString().slice(0,10):""} key={`${m.id}-end-${m.endDate||""}`} id={`mortgage-end-${m.id}`} style={styles.field}/></label><label style={styles.label}>Einde rentevaste periode<input type="date" defaultValue={m.fixedRateEndDate?new Date(m.fixedRateEndDate).toISOString().slice(0,10):""} key={`${m.id}-fixed-${m.fixedRateEndDate||""}`} id={`mortgage-fixed-${m.id}`} style={styles.field}/></label></div><button disabled={busy} onClick={()=>{const end=(document.getElementById(`mortgage-end-${m.id}`) as HTMLInputElement|null)?.value||"";const fixed=(document.getElementById(`mortgage-fixed-${m.id}`) as HTMLInputElement|null)?.value||"";void saveMortgageDates(m.id,end,fixed);}} style={{marginTop:9,border:"1px solid var(--border)",borderRadius:8,padding:"8px 11px",background:"var(--card)",color:"var(--foreground)",fontWeight:600,cursor:"pointer"}}>Datums opslaan</button></article>})}{mortgages.length===0&&<p style={styles.muted}>Nog geen gekoppelde hypotheekdelen.</p>}</div></section>
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:13}}><Icon>▣</Icon><div><h2 style={{margin:0,fontSize:19}}>Nieuwe betaling registreren</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Registreer de werkelijke maandbetaling.</p></div></div>{mortgages.length>0?<div style={{display:"grid",gap:12}}><label style={styles.label}>Hypotheekdeel<select style={styles.field} value={mortgageId} onChange={e=>setMortgageId(e.target.value)}>{mortgages.map(m=><option key={m.id} value={m.id}>{m.debt.name} — {m.name}</option>)}</select></label><label style={styles.label}>Betaaldatum<input style={styles.field} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:8}}>{input("Rente (€)",interest,setInterest,{type:"number",min:0,step:"0.01",placeholder:"0,00"})}{input("Reguliere aflossing (€)",principal,setPrincipal,{type:"number",min:0,step:"0.01",placeholder:"0,00"})}{input("Extra aflossing (€)",extra,setExtra,{type:"number",min:0,step:"0.01",placeholder:"0,00"})}</div><div style={{background:"rgba(16,185,129,.055)",border:"1px solid rgba(16,185,129,.15)",borderRadius:11,padding:13}}><strong style={{fontSize:13}}>Verwachte impact</strong><div style={{display:"grid",gridTemplateColumns:"repeat(3,minmax(0,1fr))",gap:8,marginTop:10}}><div><div style={styles.muted}>Totaal betaald</div><strong>{money(interestNum+principalNum+extraNum)}</strong></div><div><div style={styles.muted}>Nieuwe schuld</div><strong>{money(Math.max(0,(Number(selectedMortgage?.debt.currentBalance)||0)-principalNum-extraNum))}</strong></div><div><div style={styles.muted}>Netto indicatie</div><strong style={{color:"#059669"}}>{money(Math.max(0,interestNum+principalNum+extraNum-estimatedRelief))}</strong></div></div></div><label style={styles.label}>Notitie<input style={styles.field} value={note} onChange={e=>setNote(e.target.value)} placeholder="Bijv. bankafschrift oktober"/></label><button disabled={busy||!mortgageId||!date||interest===""||principal===""} onClick={addPayment} style={{border:0,borderRadius:9,padding:12,background:"#07865f",color:"white",fontWeight:650,cursor:"pointer"}}>{busy?"Opslaan…":"▣  Betaling opslaan"}</button></div>:<p style={styles.muted}>Koppel eerst een bestaande hypotheekschuld om betalingen te registreren.</p>}</section>
 </div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(0,1.5fr) minmax(290px,1fr)",gap:16,alignItems:"start"}} className="mortgage-lower-grid">
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Icon>▤</Icon><div><h2 style={{margin:0,fontSize:19}}>Hypotheekrenteaftrek & eigenwoningforfait</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Indicatieve fiscale berekening op basis van WOZ-waarde, rente en belastingpercentage.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>{input("WOZ-waarde (€)",wozValue,setWozValue,{type:"number",min:0,step:"1000"})}{input("Eigenwoningforfait (%)",eigenwoningforfaitRate,setEigenwoningforfaitRate,{type:"number",min:0,max:100,step:"0.01"})}{input("Belastingpercentage (%)",taxRate,setTaxRate,{type:"number",min:0,max:100,step:"0.01"})}{input("Belastingjaar",taxYear,setTaxYear,{type:"number",min:2000,max:2100,step:"1"})}</div><button disabled={busy||!mortgageId} onClick={saveTaxSettings} style={{marginTop:12,border:0,borderRadius:9,padding:"10px 14px",background:"#07865f",color:"white",fontWeight:650,cursor:"pointer"}}>{busy?"Opslaan…":"Fiscale gegevens opslaan"}</button><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(160px,1fr))",gap:12,marginTop:16,paddingTop:14,borderTop:"1px solid var(--border)"}}><div><div style={styles.muted}>Eigenwoningforfait / jaar</div><strong>{money(annualEigenwoningforfait)}</strong></div><div><div style={styles.muted}>Eigenwoningforfait / maand</div><strong>{money(monthlyEigenwoningforfait)}</strong></div><div><div style={styles.muted}>Belastingeffect EWF / jaar</div><strong>{money(annualEwfTax)}</strong></div><div><div style={styles.muted}>Belastingeffect EWF / maand</div><strong>{money(monthlyEwfTax)}</strong></div><div><div style={styles.muted}>Jaarlijkse rente</div><strong>{money(monthlyTotals.interest*12)}</strong></div><div><div style={styles.muted}>Netto fiscale voordeel / jaar</div><strong style={{color:"#059669"}}>{money(monthlyTotals.relief*12)}</strong></div></div><p style={{...styles.muted,fontSize:11,marginBottom:0}}>Vereenvoudigde schatting. De werkelijke belastinguitkomst kan afwijken door je fiscale situatie, aftrekbeperkingen en de fiscale behandeling van de lening.</p></section>
 <section style={{...styles.card,background:"rgba(16,185,129,.035)"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Icon>▥</Icon><div><h2 style={{margin:0,fontSize:19}}>Aflossingscalculator</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Automatische prognose van looptijd, rente, fiscale indicatie en hypotheekvrije datum.</p></div></div>{selectedMortgage&&calculator?<div style={{display:"grid",gap:12}}><label style={styles.label}>Rekenmethode<select style={styles.field} value={loanType} onChange={e=>setLoanType(e.target.value as "ANNUITY"|"LINEAR"|"INTEREST_ONLY")}><option value="ANNUITY">Annuïtair</option><option value="LINEAR">Lineair</option><option value="INTEREST_ONLY">Aflossingsvrij</option></select></label>{input("Eigen extra aflossing p/m (€)",customExtra,setCustomExtra,{type:"number",min:0,step:"10"})}<div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:8}}><div style={{padding:11,border:"1px solid var(--border)",borderRadius:9,background:"var(--card)"}}><div style={styles.muted}>Automatische rente deze maand</div><strong>{money(calculator.currentInterest)}</strong></div><div style={{padding:11,border:"1px solid var(--border)",borderRadius:9,background:"var(--card)"}}><div style={styles.muted}>Automatische aflossing deze maand</div><strong>{money(calculator.currentPrincipal)}</strong></div><div style={{padding:11,border:"1px solid var(--border)",borderRadius:9,background:"var(--card)"}}><div style={styles.muted}>Hypotheekvrij met eigen scenario</div><strong>{dateText(calculator.customProjection.payoffDate)}</strong></div><div style={{padding:11,border:"1px solid var(--border)",borderRadius:9,background:"var(--card)"}}><div style={styles.muted}>Bespaarde rente</div><strong style={{color:"#059669"}}>{money(Math.max(0,calculator.base.interest-calculator.customProjection.interest))}</strong></div></div></div>:<p style={styles.muted}>Selecteer eerst een hypotheekdeel.</p>}</section></div>
 {selectedMortgage&&calculator&&<>
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><Icon>⇄</Icon><div><h2 style={{margin:0,fontSize:19}}>Aflossen vs. beleggen</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Gekoppeld aan je echte beleggingen uit Vermogen. Je huidige beleggingswaarde is het startpunt van alle scenario’s.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:14}}><article style={{padding:12,border:"1px solid var(--border)",borderRadius:10,background:"rgba(16,185,129,.04)"}}><div style={styles.muted}>Huidige beleggingen</div><strong style={{fontSize:22,color:"#059669"}}>{money(currentInvestmentValue)}</strong><div style={{...styles.muted,fontSize:11}}>{investmentAssets.length} belegging{investmentAssets.length===1?"":"en"} uit Vermogen</div></article>{input("Eenmalig extra aflossen (€)",oneTimeExtra,setOneTimeExtra,{type:"number",min:0,step:"100"})}{input("Beleggen p/m (€)",investmentAmount,setInvestmentAmount,{type:"number",min:0,step:"10"})}{input("Verwacht rendement beleggen (%)",investmentReturn,setInvestmentReturn,{type:"number",min:-99,step:"0.1"})}</div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13,minWidth:1000}}><thead><tr>{["Scenario","Looptijd","Hypotheekvrij","Toekomstige rente","Bespaarde rente","Fiscale aftrek","Netto kaslast","Beleggingswaarde eindpunt"].map(x=><th key={x} style={{textAlign:"left",padding:"10px 9px",background:"rgba(16,185,129,.055)",borderBottom:"1px solid var(--border)",whiteSpace:"nowrap"}}>{x}</th>)}</tr></thead><tbody>{calculator.scenarios.map((s,i)=><tr key={`${s.label}-${i}`}><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)",fontWeight:600}}>{s.label}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)"}}>{durationText(s.months)}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)",whiteSpace:"nowrap"}}>{dateText(s.payoffDate)}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)"}}>{money(s.interest)}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)",color:s.interestSaved>0?"#059669":undefined}}>{money(s.interestSaved)}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)"}}>{money(s.taxRelief)}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)"}}>{money(s.netCost)}</td><td style={{padding:"10px 9px",borderBottom:"1px solid var(--border)"}}>{money(s.investment)}</td></tr>)}</tbody></table></div><p style={{...styles.muted,fontSize:11,marginBottom:0}}>De huidige waarde van assets met type INVESTMENT uit Vermogen wordt automatisch als startvermogen gebruikt. Het gekozen rendement is een scenario-aanname, geen garantie.</p></section>
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:14}}><Icon>⚖</Icon><div><h2 style={{margin:0,fontSize:19}}>Netto vermogensvergelijking</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Extra aflossen versus maandelijks beleggen, inclusief indicatieve hypotheekrenteaftrek, eigenwoningforfait en een vereenvoudigde Box 3-projectie.</p></div></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginBottom:14}}>{input("Box 3 tarief (%)",box3Rate,setBox3Rate,{type:"number",min:0,max:100,step:"0.1"})}{input("Heffingsvrij resultaat (€)",box3ExemptResult,setBox3ExemptResult,{type:"number",min:0,step:"100"})}{input("Nieuw stelsel vanaf jaar",box3StartYear,setBox3StartYear,{type:"number",min:new Date().getFullYear(),step:"1"})}<article style={{padding:12,border:"1px solid var(--border)",borderRadius:10,background:"rgba(59,130,246,.04)"}}><div style={styles.muted}>Aannames</div><strong style={{fontSize:16}}>Werkelijk rendement</strong><div style={{...styles.muted,fontSize:11}}>Box 3 wordt alleen vanaf het ingestelde jaar toegepast.</div></article></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10,marginBottom:14}}>{metric("↓","Box 3 – aflossen",money(calculator.repayBox3Total),"Cumulatieve indicatie")}{metric("↗","Box 3 – beleggen",money(calculator.investBox3Total),"Cumulatieve indicatie")}{metric("%","EWF per jaar",money(annualEigenwoningforfait),"Bij huidige WOZ/EWF-instelling")}{metric("€","EWF belastingeffect",money(annualEwfTax),"Indicatief per jaar")}</div>
 <div style={{overflowX:"auto",maxHeight:560}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:12,minWidth:1250}}><thead style={{position:"sticky",top:0,background:"var(--card)"}}><tr>{["Jaar","Hypotheek aflossen","Hypotheek beleggen","Beleggingen aflossen","Beleggingen beleggen","Box 3 aflossen","Box 3 beleggen","HRA/EWF aflossen","HRA/EWF beleggen","Netto vermogen aflossen","Netto vermogen beleggen","Verschil beleggen - aflossen"].map(x=><th key={x} style={{textAlign:"left",padding:"9px 8px",borderBottom:"1px solid var(--border)",whiteSpace:"nowrap"}}>{x}</th>)}</tr></thead><tbody>{calculator.strategyYears.map(y=><tr key={y.year}><td style={{padding:"9px 8px",borderBottom:"1px solid var(--border)",fontWeight:700}}>{y.year}</td>{[money(y.repayBalance),money(y.investBalance),money(y.repayInvestment),money(y.investInvestment),money(y.repayBox3),money(y.investBox3),money(y.repayTaxRelief),money(y.investTaxRelief),money(y.repayNetWorth),money(y.investNetWorth)].map((v,i)=><td key={i} style={{padding:"9px 8px",borderBottom:"1px solid var(--border)",whiteSpace:"nowrap"}}>{v}</td>)}<td style={{padding:"9px 8px",borderBottom:"1px solid var(--border)",fontWeight:700,color:y.difference>=0?"#059669":"#b45309",whiteSpace:"nowrap"}}>{money(y.difference)}</td></tr>)}</tbody></table></div>
 <p style={{...styles.muted,fontSize:11,lineHeight:1.55,marginBottom:0}}>Deze vergelijking is een planningsmodel. Voor Box 3 wordt per kalenderjaar het berekende beleggingsrendement verminderd met het ingestelde heffingsvrije resultaat en daarna belast tegen het ingestelde tarief; de berekende belasting wordt van de belegging afgetrokken. Verliesverrekening, uitzonderingen, andere Box 3-bezittingen/schulden en overgangsregels zijn niet gemodelleerd. De eigen woning blijft in deze planner in Box 1; hypotheekrenteaftrek en EWF worden daarom apart verwerkt. Vrijvallende hypotheeklasten na vervroegd aflossen worden niet automatisch herbelegd.</p></section>
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Icon>⌁</Icon><div><h2 style={{margin:0,fontSize:19}}>Hypotheekprognose</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Grijs = huidige planning. Groen = jouw extra-aflossingsscenario.</p></div></div><ProjectionChart base={calculator.base.rows} extra={calculator.customProjection.rows} fixedRateEndDate={selectedMortgage.fixedRateEndDate} endDate={selectedMortgage.endDate}/><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10,marginTop:12}}>{metric("⌛","Resterende looptijd",durationText(calculator.customProjection.months),`${durationText(Math.max(0,calculator.base.months-calculator.customProjection.months))} sneller`)}{metric("✓","Hypotheekvrij",dateText(calculator.customProjection.payoffDate),"Volgens gekozen scenario",true)}{metric("%","Rente bespaard",money(Math.max(0,calculator.base.interest-calculator.customProjection.interest)),"Ten opzichte van basis")}{metric("€","Eenmalige aflossing",money(calculator.oneTime),"Direct verwerkt in prognose")}</div></section>
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Icon>▦</Icon><div><h2 style={{margin:0,fontSize:19}}>Jaarlijkse hypotheekplanning</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Jaaroverzicht van jouw gekozen extra-aflossingsscenario.</p></div></div><div style={{overflowX:"auto",maxHeight:520}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13,minWidth:900}}><thead style={{position:"sticky",top:0,background:"var(--card)"}}><tr>{["Jaar","Eindsaldo","Rente","Reguliere aflossing","Extra aflossing","Renteaftrek indicatie","Netto kaslast"].map(x=><th key={x} style={{textAlign:"left",padding:"10px 9px",borderBottom:"1px solid var(--border)"}}>{x}</th>)}</tr></thead><tbody>{calculator.yearly.map(y=><tr key={y.year}><td style={{padding:"9px",borderBottom:"1px solid var(--border)",fontWeight:600}}>{y.year}</td>{[money(y.endBalance),money(y.interest),money(y.principal),money(y.extra),money(y.taxRelief),money(y.net)].map((v,i)=><td key={i} style={{padding:"9px",borderBottom:"1px solid var(--border)"}}>{v}</td>)}</tr>)}</tbody></table></div></section>
 <section style={{...styles.card,background:"rgba(16,185,129,.035)"}}><div style={{display:"flex",alignItems:"center",gap:10,marginBottom:12}}><Icon>◎</Icon><div><h2 style={{margin:0,fontSize:19}}>Planner-check</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Snelle controle of de huidige maandtermijn past bij de ingevoerde einddatum.</p></div></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:10}}><div><div style={styles.muted}>Huidige maandtermijn</div><strong>{money(calculator.payment)}</strong></div><div><div style={styles.muted}>Benodigde extra p/m tot einddatum</div><strong>{money(calculator.requiredExtra)}</strong></div><div><div style={styles.muted}>Rente deze maand</div><strong>{money(calculator.currentInterest)}</strong></div><div><div style={styles.muted}>Aflossing deze maand</div><strong>{money(calculator.currentPrincipal)}</strong></div></div></section>
 </>}
 {available.length>0&&<section style={styles.card}><h2 style={{margin:"0 0 10px",fontSize:18}}>Bestaande hypotheekschuld koppelen</h2><div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr) minmax(0,1fr) auto",gap:9}}><select style={styles.field} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecteer schuld</option>{available.map(d=><option key={d.id} value={d.id}>{d.name} — {money(Number(d.currentBalance))}</option>)}</select><input style={styles.field} value={name} onChange={e=>setName(e.target.value)} aria-label="Naam hypotheek"/><button disabled={!selected||busy} onClick={link} style={{border:0,borderRadius:9,padding:"9px 14px",background:"#07865f",color:"white",fontWeight:600}}>Koppel</button></div></section>}
 {editingPayment&&<section style={{...styles.card,borderColor:"rgba(16,185,129,.45)"}}><h2 style={{margin:"0 0 12px",fontSize:18}}>Betaling bewerken</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}>{input("Betaaldatum",editingPayment.date,v=>setEditingPayment({...editingPayment,date:v}),{type:"date"})}{input("Rente (€)",editingPayment.interestAmount,v=>setEditingPayment({...editingPayment,interestAmount:v}),{type:"number",min:0,step:"0.01"})}{input("Reguliere aflossing (€)",editingPayment.principalAmount,v=>setEditingPayment({...editingPayment,principalAmount:v}),{type:"number",min:0,step:"0.01"})}{input("Extra aflossing (€)",editingPayment.extraPrincipal,v=>setEditingPayment({...editingPayment,extraPrincipal:v}),{type:"number",min:0,step:"0.01"})}{input("Aftrek (schatting €)",editingPayment.taxReliefEstimate,v=>setEditingPayment({...editingPayment,taxReliefEstimate:v}),{type:"number",min:0,step:"0.01"})}</div><label style={{...styles.label,marginTop:10}}>Notitie<input style={styles.field} value={editingPayment.note} onChange={e=>setEditingPayment({...editingPayment,note:e.target.value})}/></label><div style={{display:"flex",gap:8,marginTop:12,flexWrap:"wrap"}}><button disabled={busy} onClick={saveEdit} style={{border:0,borderRadius:8,padding:"10px 14px",background:"#07865f",color:"white",fontWeight:650}}>Wijzigingen opslaan</button><button disabled={busy} onClick={()=>setEditingPayment(null)} style={{border:"1px solid var(--border)",borderRadius:8,padding:"10px 14px",background:"var(--card)",color:"var(--foreground)"}}>Annuleren</button></div><p style={{...styles.muted,marginBottom:0}}>Bij opslaan wordt het verschil in reguliere en extra aflossing verwerkt in de actuele hypotheekschuld. Rente verandert de schuld niet.</p></section>}
 <section style={styles.card}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10,marginBottom:10}}><div><h2 style={{margin:0,fontSize:19}}>Betalingshistorie</h2><p style={{...styles.muted,margin:"2px 0 0"}}>Overzicht van geregistreerde rente, aflossing en extra aflossingen.</p></div><span style={{fontSize:12,color:"#047857"}}>Alle hypotheekdelen</span></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13,minWidth:760}}><thead><tr>{["Datum","Hypotheekdeel","Rente","Aflossing","Extra aflossing","Totaal betaald","Aftrek (indicatie)","Acties"].map(x=><th key={x} style={{textAlign:"left",padding:"10px 9px",background:"rgba(16,185,129,.055)",borderBottom:"1px solid var(--border)",color:"var(--muted-foreground)",fontWeight:600}}>{x}</th>)}</tr></thead><tbody>{mortgages.flatMap(m=>(m.payments||[]).map(p=><tr key={p.id}>{[new Date(p.date).toLocaleDateString("nl-NL"),m.debt.name,money(Number(p.interestAmount)),money(Number(p.principalAmount)),money(Number(p.extraPrincipal)),money(Number(p.interestAmount)+Number(p.principalAmount)+Number(p.extraPrincipal)),money(Number(p.taxReliefEstimate))].map((v,i)=><td key={i} style={{padding:"11px 9px",borderBottom:"1px solid var(--border)",whiteSpace:"nowrap"}}>{v}</td>)}<td style={{padding:"8px",borderBottom:"1px solid var(--border)",whiteSpace:"nowrap"}}><button disabled={busy} onClick={()=>beginEdit(m,p)} style={{border:"1px solid var(--border)",borderRadius:7,padding:"6px 9px",background:"var(--card)",color:"var(--foreground)",cursor:"pointer",marginRight:5}}>Bewerken</button><button disabled={busy} onClick={()=>void removePayment(p.id)} style={{border:"1px solid #fecaca",borderRadius:7,padding:"6px 9px",background:"#fff7f7",color:"#b91c1c",cursor:"pointer"}}>Verwijderen</button></td></tr>))}</tbody></table>{mortgages.every(m=>!m.payments?.length)&&<p style={styles.muted}>Nog geen betalingen geregistreerd.</p>}</div></section>
 <style jsx>{`@media(max-width:850px){.mortgage-main-grid,.mortgage-lower-grid{grid-template-columns:1fr!important}} @media(max-width:560px){main{padding:16px!important}.mortgage-main-grid,.mortgage-lower-grid{grid-template-columns:1fr!important}}`}</style>
 </main>;
}
