"use client";
import { useEffect, useMemo, useState } from "react";

type Debt = { id:string; name:string; currentBalance:string|number; interestRate:string|number|null; monthlyPayment:string|number|null };
type Payment = { id:string; date:string; interestAmount:string|number; principalAmount:string|number; extraPrincipal:string|number; taxReliefEstimate:string|number; note?:string|null };
type Mortgage = { id:string; name:string; debt:Debt; payments:Payment[]; loanParts:unknown[]; balanceHistory:unknown[]; extraPayments:unknown[] };
const money=(v:number)=>new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(Number.isFinite(v)?v:0);
const field:React.CSSProperties={width:"100%",padding:10,border:"1px solid var(--border)",borderRadius:8,background:"var(--card)",color:"var(--foreground)",boxSizing:"border-box"};
const card:React.CSSProperties={border:"1px solid var(--border)",borderRadius:12,padding:16,minWidth:0};
export default function HypotheekPage(){
 const [mortgages,setMortgages]=useState<Mortgage[]>([]),[available,setAvailable]=useState<Debt[]>([]),[selected,setSelected]=useState(""),[name,setName]=useState("Mijn hypotheek"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const [mortgageId,setMortgageId]=useState(""),[date,setDate]=useState(new Date().toISOString().slice(0,10)),[interest,setInterest]=useState(""),[principal,setPrincipal]=useState(""),[extra,setExtra]=useState("0"),[taxRate,setTaxRate]=useState("36.97"),[annualIncome,setAnnualIncome]=useState(""),[eigenwoningforfait,setEwf]=useState("0"),[note,setNote]=useState("");
 async function load(){setError("");try{const r=await fetch("/api/mortgage");const d=await r.json();if(!r.ok)throw Error(d.error||"Ophalen mislukt");setMortgages(d.mortgages||[]);setAvailable(d.availableDebts||[]);if(!mortgageId&&d.mortgages?.[0])setMortgageId(d.mortgages[0].id);}catch(e){setError(e instanceof Error?e.message:"Fout");}}
 useEffect(()=>{void load();},[]);
 const selectedMortgage=mortgages.find(m=>m.id===mortgageId);
 const taxRateNum=Math.max(0,Math.min(100,Number(taxRate)||0))/100;
 const ewfMonthly=Math.max(0,Number(eigenwoningforfait)||0)/12;
 const monthlyEstimates=useMemo(()=>mortgages.map(m=>{
   const balance=Number(m.debt.currentBalance)||0, rate=Math.max(0,Number(m.debt.interestRate)||0), gross=Math.max(0,Number(m.debt.monthlyPayment)||0);
   const interestEstimate=balance*rate/1200;
   const relief=Math.max(0,interestEstimate-ewfMonthly)*taxRateNum;
   return {id:m.id,balance,rate,gross,interestEstimate,relief,net:Math.max(0,gross-relief),hasPayment:m.debt.monthlyPayment!==null&&m.debt.monthlyPayment!==undefined&&m.debt.monthlyPayment!==""};
 }),[mortgages,taxRateNum,ewfMonthly]);
 const monthlyTotals=monthlyEstimates.reduce((a,x)=>({gross:a.gross+x.gross,interest:a.interest+x.interestEstimate,relief:a.relief+x.relief,net:a.net+x.net}),{gross:0,interest:0,relief:0,net:0});
 const totals=useMemo(()=>mortgages.reduce((a,m)=>{a.balance+=Number(m.debt.currentBalance);a.interest+=m.payments.reduce((x,p)=>x+Number(p.interestAmount),0);a.principal+=m.payments.reduce((x,p)=>x+Number(p.principalAmount)+Number(p.extraPrincipal),0);a.relief+=m.payments.reduce((x,p)=>x+Number(p.taxReliefEstimate),0);return a;},{balance:0,interest:0,principal:0,relief:0}),[mortgages]);
 const interestNum=Number(interest||0), principalNum=Number(principal||0), extraNum=Number(extra||0);
 const estimatedRelief=Math.max(0,interestNum-ewfMonthly)*taxRateNum;
 async function link(){setBusy(true);setError("");try{const r=await fetch("/api/mortgage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({debtId:selected,name})});const d=await r.json();if(!r.ok)throw Error(d.error||"Koppelen mislukt");await load();}catch(e){setError(e instanceof Error?e.message:"Fout");}finally{setBusy(false);}}
 async function addPayment(){setBusy(true);setError("");setNotice("");try{const r=await fetch("/api/mortgage",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"createPayment",mortgageId,date,interestAmount:interest,principalAmount:principal,extraPrincipal:extra,taxReliefEstimate:estimatedRelief,note})});const d=await r.json();if(!r.ok)throw Error(d.error||"Opslaan mislukt");setNotice(`Betaling opgeslagen. Nieuw saldo: ${money(Number(d.newBalance))}`);setInterest("");setPrincipal("");setExtra("0");setNote("");await load();}catch(e){setError(e instanceof Error?e.message:"Fout");}finally{setBusy(false);}}
 return <main style={{width:"100%",maxWidth:1180,margin:"0 auto",padding:24,display:"grid",gap:20,boxSizing:"border-box"}}>
 <header><h1 style={{fontSize:30,fontWeight:700,margin:0}}>Hypotheek</h1><p style={{color:"var(--muted-foreground)",marginTop:6}}>Overzicht van bruto en netto maandlasten, met aparte registratie van rente en aflossing.</p></header>
 {error&&<p role="alert" style={{color:"#dc2626"}}>{error}</p>}{notice&&<p role="status" style={{color:"#16a34a"}}>{notice}</p>}
 <section style={{...card,display:"grid",gap:12}}><div><h2 style={{fontSize:19,fontWeight:650,margin:0}}>Netto maandlast — indicatie</h2><p style={{fontSize:13,color:"var(--muted-foreground)",margin:"5px 0 0"}}>Gebaseerd op de ingevoerde maandtermijnen, actuele saldi en jouw fiscale aannames. Geen definitieve belastingberekening.</p></div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{[["Bruto maandtermijn",money(monthlyTotals.gross)], ["Geschatte rente per maand",money(monthlyTotals.interest)], ["Geschatte renteaftrek",`− ${money(monthlyTotals.relief)}`], ["Geschatte netto maandlast",money(monthlyTotals.net)]].map(([label,value],i)=><article key={label} style={{border:"1px solid var(--border)",borderRadius:10,padding:14,background:i===3?"var(--muted)":"var(--card)"}}><div style={{fontSize:13,color:"var(--muted-foreground)"}}>{label}</div><strong style={{fontSize:22,display:"block",marginTop:5,color:i===3?"var(--success, #15803d)":"var(--foreground)"}}>{value}</strong></article>)}</div>
 {monthlyEstimates.some(x=>!x.hasPayment)&&<p style={{fontSize:13,color:"var(--muted-foreground)",margin:0}}>Voor hypotheekdelen zonder ingevulde maandtermijn kan Finwise de netto maandlast nog niet bepalen. Vul de maandtermijn bij de bijbehorende schuld in.</p>}
 <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}><label style={{fontSize:13}}>Geschat aftrektarief (%)<input style={field} type="number" min="0" max="100" step="0.01" value={taxRate} onChange={e=>setTaxRate(e.target.value)}/></label><label style={{fontSize:13}}>Jaarlijks eigenwoningforfait (€)<input style={field} type="number" min="0" step="1" value={eigenwoningforfait} onChange={e=>setEwf(e.target.value)}/></label><label style={{fontSize:13}}>Jaarinkomen (optioneel, ter referentie)<input style={field} type="number" min="0" value={annualIncome} onChange={e=>setAnnualIncome(e.target.value)}/></label></div>
 <p style={{fontSize:12,color:"var(--muted-foreground)",margin:0}}>Vereenvoudigde schatting: maandrente = actueel saldo × rentepercentage / 12. Eigenwoningforfait wordt hier als maandelijkse vermindering op de rentebasis benaderd. Controleer fiscale uitkomsten met je eigen aangifte of adviseur.</p></section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{[["Totale hypotheekschuld",money(totals.balance)],["Geregistreerde rente",money(totals.interest)],["Geregistreerde aflossing",money(totals.principal)],["Geregistreerde aftrek (schatting)",money(totals.relief)]].map(([label,value])=><article key={label} style={card}><div style={{fontSize:13,color:"var(--muted-foreground)"}}>{label}</div><strong style={{fontSize:21}}>{value}</strong></article>)}</section>
 <section style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:12}}>{mortgages.map(m=>{const estimate=monthlyEstimates.find(x=>x.id===m.id)!;return <article key={m.id} style={card}><h2 style={{fontSize:19,fontWeight:650,margin:"0 0 8px"}}>{m.name}</h2><p style={{margin:"0 0 12px",color:"var(--muted-foreground)"}}>{m.debt.name} · Rente {m.debt.interestRate??"—"}%</p><strong style={{fontSize:24}}>{money(estimate.balance)}</strong><div style={{fontSize:13,color:"var(--muted-foreground)",marginTop:8}}>Maandtermijn: {estimate.hasPayment?money(estimate.gross):"Niet ingesteld"}</div><div style={{fontSize:13,marginTop:4}}>Geschatte netto termijn: <strong>{estimate.hasPayment?money(estimate.net):"—"}</strong></div><div style={{fontSize:13,marginTop:4}}>Geschatte rente per maand: {money(estimate.interestEstimate)}</div></article>;})}</section>
 {available.length>0&&<section style={{...card,display:"grid",gap:10}}><h2 style={{fontSize:20,fontWeight:650,margin:0}}>Bestaande hypotheekschuld koppelen</h2><select style={field} value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Selecteer schuld</option>{available.map(d=><option key={d.id} value={d.id}>{d.name} — {money(Number(d.currentBalance))}</option>)}</select><input style={field} value={name} onChange={e=>setName(e.target.value)} aria-label="Naam hypotheek"/><button disabled={!selected||busy} onClick={link}>Koppel hypotheek</button></section>}
 {mortgages.length>0&&<section style={{...card,display:"grid",gap:10}}><h2 style={{fontSize:20,fontWeight:650,margin:0}}>Werkelijke betaling registreren</h2><label>Hypotheek<select style={field} value={mortgageId} onChange={e=>setMortgageId(e.target.value)}>{mortgages.map(m=><option key={m.id} value={m.id}>{m.name} — {m.debt.name}</option>)}</select></label><label>Betaaldatum<input style={field} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:10}}><label>Rente (€)<input style={field} type="number" min="0" step="0.01" value={interest} onChange={e=>setInterest(e.target.value)}/></label><label>Reguliere aflossing (€)<input style={field} type="number" min="0" step="0.01" value={principal} onChange={e=>setPrincipal(e.target.value)}/></label><label>Extra aflossing (€)<input style={field} type="number" min="0" step="0.01" value={extra} onChange={e=>setExtra(e.target.value)}/></label></div><div style={{border:"1px solid var(--border)",borderRadius:10,padding:12,display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(150px,1fr))",gap:8}}><div><small style={{color:"var(--muted-foreground)"}}>Bruto betaling</small><strong style={{display:"block"}}>{money(interestNum+principalNum+extraNum)}</strong></div><div><small style={{color:"var(--muted-foreground)"}}>Geschatte aftrek</small><strong style={{display:"block"}}>{money(estimatedRelief)}</strong></div><div><small style={{color:"var(--muted-foreground)"}}>Netto indicatie</small><strong style={{display:"block"}}>{money(Math.max(0,interestNum+principalNum+extraNum-estimatedRelief))}</strong></div></div><label>Notitie<input style={field} value={note} onChange={e=>setNote(e.target.value)} placeholder="Bijv. bankafschrift oktober"/></label><button disabled={busy||!mortgageId||!date||interest===""||principal===""} onClick={addPayment}>Betaling opslaan en saldo bijwerken</button></section>}
 {mortgages.map(m=><section key={`${m.id}-history`} style={card}><h2 style={{fontSize:20,fontWeight:650,margin:"0 0 10px"}}>Betalingshistorie — {m.name}</h2>{!m.payments?.length?<p>Nog geen betalingen geregistreerd.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:14}}><thead><tr>{["Datum","Rente","Aflossing","Extra","Aftrek schatting","Totaal betaald"].map(x=><th key={x} style={{textAlign:"left",padding:8,borderBottom:"1px solid var(--border)"}}>{x}</th>)}</tr></thead><tbody>{m.payments.map(p=><tr key={p.id}>{[new Date(p.date).toLocaleDateString("nl-NL"),money(Number(p.interestAmount)),money(Number(p.principalAmount)),money(Number(p.extraPrincipal)),money(Number(p.taxReliefEstimate)),money(Number(p.interestAmount)+Number(p.principalAmount)+Number(p.extraPrincipal))].map((x,i)=><td key={i} style={{padding:8,borderBottom:"1px solid var(--border)"}}>{x}</td>)}</tr>)}</tbody></table></div>}</section>)}
 <aside style={{fontSize:12,color:"var(--muted-foreground)"}}>Let op: het registreren van een betaling verlaagt direct de gekoppelde hypotheekschuld met reguliere plus extra aflossing. Rente verlaagt de schuld niet. Maak vóór gebruik een databaseback-up. Netto maandlasten zijn indicatief.</aside>
 </main>;
}
